In [1]:
import pandas as pd
dataset = pd.read_csv('CKD.csv')

In [2]:
dataset.shape

(399, 25)

In [3]:
dataset.head(5)

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.0,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.0,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.0,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.0,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.0,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes

In [4]:
dataset=pd.get_dummies(dataset, dtype=int, drop_first=True)

In [5]:
dataset.shape

(399, 28)

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dependent=dataset[['classification_yes']]

In [8]:
dependent.value_counts()

classification_yes
1                     249
0                     150
Name: count, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')
param_grid={'criterion':['gini', 'entropy', 'log_loss'],
           'splitter':['best', 'random'],
           'max_features':['sqrt', 'log2',None]}
grid = GridSearchCV(DecisionTreeClassifier(),param_grid,refit=True,n_jobs=-1,verbose=3,scoring='f1_weighted')

In [12]:
grid.fit(X_train,y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['sqrt', 'log2', None],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [13]:
y_pred = grid.predict(X_test)

In [14]:
grid_result = grid.cv_results_

In [15]:
table = pd.DataFrame.from_dict(grid_result)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.011866,0.002278,0.026616,0.005179,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.908501,0.962264,0.944023,0.961826,0.943093,0.943941,0.019557,13
1,0.009012,0.002149,0.026466,0.003185,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",1.000000,0.962264,1.000000,0.981031,0.943651,0.977389,0.021922,1
2,0.007301,0.000957,0.024857,0.003417,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.963284,0.923510,0.962573,0.962264,0.981217,0.958570,0.018942,9
3,0.009511,0.002621,0.027667,0.001662,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.981378,0.924528,0.962573,0.981031,1.000000,0.969902,0.025589,4
4,0.011512,0.004443,0.029275,0.001815,gini,None,best,"{'criterion': 'gini', 'max_features': None, 's...",0.981378,0.961755,0.962573,0.943093,0.942332,0.958226,0.014485,10
5,0.009775,0.001932,0.026800,0.002780,gini,None,random,"{'criterion': 'gini', 'max_features': None, 's...",0.981569,0.925272,0.925524,0.943093,0.981217,0.951335,0.025379,11
6,0.009132,0.002023,0.026957,0.002102,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.945100,0.961755,0.962573,0.906085,0.962264,0.947556,0.021768,12
7,0.007487,0.001808,0.021143,0.002367,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.963284,0.981014,0.925524,0.981217,0.962573,0.962722,0.020301,6
8,0.005570,0.001168,0.019229,0.002675,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.907846,0.962264,1.000000,0.962264,0.981217,0.962718,0.030801,7
9,0.007252,0.000690,0.021841,0.001934,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.963284,0.943041,0.868519,0.962264,0.981031,0.943628,0.039432,14
10,0.008602,0.001277,0.021386,0.002694,entropy,None,best,"{'criterion': 'entropy', 'max_features': None,...",0.890467,0.942166,0.944023,0.922492,0.962264,0.932282,0.024408,17
11,0.005420,0.001550,0.018962,0.002851,entropy,None,random,"{'criterion': 'entropy', 'max_features': None,...",0.945100,0.943699,0.851225,0.981217,0.981217,0.940492,0.047575,15
12,0.006911,0.001306,0.019786,0.002547,log_loss,sqrt,best,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.963284,0.962264,0.907035,0.981031,1.000000,0.962723,0.031069,5
13,0.005102,0.000850,0.019862,0.003508,log_loss,sqrt,random,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.981569,0.962636,0.925146,1.000000,0.981031,0.970076,0.025384,3
14,0.007722,0.000931,0.023977,0.001854,log_loss,log2,best,"{'criterion': 'log_loss', 'max_features': 'log...",0.908501,0.981014,0.907035,0.943651,0.942332,0.936507,0.027272,16
15,0.007676,0.000789,0.023568,0.002205,log_loss,log2,random,"{'criterion': 'log_loss', 'max_features': 'log...",0.981569,1.000000,0.906085,0.981031,0.925146,0.958766,0.036391,8
16,0.009185,0.001741,0.023134,0.002722,log_loss,None,best,"{'criterion': 'log_loss', 'max_features': None...",0.908877,0.922185,0.944023,0.942332,0.942332,0.931950,0.014064,18
17,0.006180,0.001721,0.014090,0.003029,log_loss,None,random,"{'criterion': 'log_loss', 'max_features': None...",1.000000,0.943041,0.981031,0.962573,1.000000,0.977329,0.022068,2

In [17]:
grid.best_params_

{'criterion': 'gini', 'max_features': 'sqrt', 'splitter': 'random'}

In [18]:
from sklearn.metrics import confusion_matrix, classification_report, f1_score, roc_auc_score

In [19]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[51  0]
 [ 5 77]]

Type1 error is 0 in the above confusion_matrix. And Type2 error is 5.

In [20]:
clf=classification_report(y_test,y_pred)
print(clf)

              precision    recall  f1-score   support

           0       0.91      1.00      0.95        51
           1       1.00      0.94      0.97        82

    accuracy                           0.96       133
   macro avg       0.96      0.97      0.96       133
weighted avg       0.97      0.96      0.96       133

Accuracy on the above result is 96% which is good.

In [21]:
f1score = f1_score(y_test,y_pred)
print(f1score)

0.9685534591194969

F1score value is closer to 96.8% which is good.

In [22]:
roc_auc_score1 = roc_auc_score(y_test, grid.predict_proba(X_test)[:,1])
print(roc_auc_score1)

0.9695121951219512