In [1]:
import pandas as pd
dataset = pd.read_csv('CKD.csv')

In [2]:
dataset.shape

(399, 25)

In [3]:
dataset.head(5)

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.0,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.0,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.0,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.0,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.0,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes

In [4]:
dataset=pd.get_dummies(dataset, dtype=int, drop_first=True)

In [5]:
dataset.shape

(399, 28)

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dependent=dataset[['classification_yes']]

In [8]:
dependent.value_counts()

classification_yes
1                     249
0                     150
Name: count, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')
param_grid={'criterion':['gini', 'entropy', 'log_loss'],
           'n_estimators':[10, 100],
           'max_features':['sqrt', 'log2',None]}
grid = GridSearchCV(RandomForestClassifier(),param_grid,refit=True,n_jobs=-1,verbose=3,scoring='f1_weighted')

In [12]:
grid.fit(X_train,y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['sqrt', 'log2', None],
                         'n_estimators': [10, 100]},
             scoring='f1_weighted', verbose=3)

In [13]:
y_pred = grid.predict(X_test)

In [14]:
grid_result = grid.cv_results_

In [15]:
table = pd.DataFrame.from_dict(grid_result)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.078224,0.003650,0.034672,0.003050,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.981569,0.981014,0.962573,0.962264,1.000000,0.977484,0.014072,3
1,0.558645,0.033870,0.054381,0.008886,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.981569,0.942166,0.962573,0.981031,0.981031,0.969674,0.015534,10
2,0.061346,0.008257,0.026511,0.001456,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.961755,0.981217,0.981031,0.943651,0.973531,0.019222,7
3,0.545752,0.028178,0.041681,0.004267,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",0.981569,0.981014,0.944023,0.981031,1.000000,0.977527,0.018266,2
4,0.065502,0.004090,0.025274,0.001644,gini,None,10,"{'criterion': 'gini', 'max_features': None, 'n...",0.926567,0.942166,0.907035,0.961826,0.981031,0.943725,0.025932,16
5,0.602906,0.012087,0.047918,0.004168,gini,None,100,"{'criterion': 'gini', 'max_features': None, 'n...",0.944707,0.942166,0.944023,0.922492,0.981031,0.946884,0.018954,15
6,0.060726,0.006236,0.024698,0.003027,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.963284,0.942166,0.962573,0.962264,0.981031,0.962264,0.012307,12
7,0.540953,0.010541,0.044270,0.002401,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.000000,0.961755,0.944023,0.981031,1.000000,0.977362,0.021879,4
8,0.059131,0.002482,0.026213,0.002267,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.908877,0.961755,0.962573,0.981217,1.000000,0.962884,0.030436,11
9,0.535239,0.013461,0.045903,0.004194,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.961755,0.981217,0.981031,1.000000,0.984801,0.014284,1
10,0.067000,0.002418,0.028277,0.003448,entropy,None,10,"{'criterion': 'entropy', 'max_features': None,...",0.962963,0.942166,0.869925,0.922492,1.000000,0.939509,0.043238,18
11,0.645441,0.005799,0.047389,0.002495,entropy,None,100,"{'criterion': 'entropy', 'max_features': None,...",0.944707,0.942166,0.925524,0.922492,0.981031,0.943184,0.020860,17
12,0.064153,0.006965,0.029946,0.003584,log_loss,sqrt,10,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.981569,0.961755,0.962573,0.962264,0.981031,0.969838,0.009364,9
13,0.571788,0.017111,0.049826,0.005307,log_loss,sqrt,100,"{'criterion': 'log_loss', 'max_features': 'sqr...",1.000000,0.942166,0.981217,0.962264,0.981031,0.973336,0.019629,8
14,0.067665,0.005871,0.041610,0.012618,log_loss,log2,10,"{'criterion': 'log_loss', 'max_features': 'log...",0.981569,0.943041,0.962573,0.981031,1.000000,0.973643,0.019345,6
15,0.539954,0.008664,0.043143,0.005400,log_loss,log2,100,"{'criterion': 'log_loss', 'max_features': 'log...",1.000000,0.942166,0.981217,0.962264,1.000000,0.977129,0.022389,5
16,0.072029,0.001870,0.029749,0.007825,log_loss,None,10,"{'criterion': 'log_loss', 'max_features': None...",0.963284,0.961755,0.925524,0.942332,0.981031,0.954785,0.019084,13
17,0.399994,0.027379,0.020625,0.002782,log_loss,None,100,"{'criterion': 'log_loss', 'max_features': None...",0.963284,0.942166,0.925524,0.922492,0.981031,0.946899,0.022398,14

In [17]:
grid.best_params_

{'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}

In [18]:
from sklearn.metrics import confusion_matrix, classification_report, f1_score, roc_auc_score

In [19]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[50  1]
 [ 1 81]]

Type1 error is 1 in the above confusion_matrix. And Type2 error is 1. Looks good on this resullt

In [20]:
clf=classification_report(y_test,y_pred)
print(clf)

              precision    recall  f1-score   support

           0       0.98      0.98      0.98        51
           1       0.99      0.99      0.99        82

    accuracy                           0.98       133
   macro avg       0.98      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133

Accuracy on the above result is 98% which is very good.

In [21]:
f1score = f1_score(y_test,y_pred)
print(f1score)

0.9878048780487805

F1score value is closer to 98.78% which is very good.

In [22]:
roc_auc_score1 = roc_auc_score(y_test, grid.predict_proba(X_test)[:,1])
print(roc_auc_score1)

0.9997608799617408

Roc_Auc_score is also 99.97%. This is also very good.