In [1]:
import pickle as pkl
import pandas as pd

In [2]:
dataset = pd.read_csv("CKD.csv")

In [3]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [4]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [5]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dependent=dataset[['classification_yes']]

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [8]:
loaded_model = pkl.load(open("Finalized_Assignment_classifier.sav",'rb'))

In [9]:
loaded_columns = pkl.load(open("columns.sav",'rb'))

In [10]:
input = {
    'age': 48,
    'bp': 80,
    'sg': 'a',
    'al': 1,
    'su': 0,
    'rbc': 'normal',
    'pc': 'normal',
    'pcc': 'notpresent',
    'ba': 'notpresent',
    'bgr': 121,
    'bu': 36,
    'sc': 1.2,
    'sod': 135,
    'pot': 4.5,
    'hemo': 15.4,
    'pcv': 44,
    'wc': 7800,
    'rc': 5.2,
    'htn': 'yes',
    'dm': 'no',
    'cad': 'no',
    'appet': 'good',
    'pe': 'no',
    'ane': 'no'
}

In [11]:
input_df=pd.DataFrame([input])

In [12]:
input_df.columns

Index(['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane'],
      dtype='object')

In [13]:
input_df

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane
0,48,80,a,1,0,normal,normal,notpresent,notpresent,121,...,15.4,44,7800,5.2,yes,no,no,good,no,no

In [14]:
input_df=pd.get_dummies(input_df,dtype=int)

In [15]:
input_df.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv',
       'wc', 'rc', 'sg_a', 'rbc_normal', 'pc_normal', 'pcc_notpresent',
       'ba_notpresent', 'htn_yes', 'dm_no', 'cad_no', 'appet_good', 'pe_no',
       'ane_no'],
      dtype='object')

In [16]:
input_df

,age,bp,al,su,bgr,bu,sc,sod,pot,hemo,...,rbc_normal,pc_normal,pcc_notpresent,ba_notpresent,htn_yes,dm_no,cad_no,appet_good,pe_no,ane_no
0,48,80,1,0,121,36,1.2,135,4.5,15.4,...,1,1,1,1,1,1,1,1,1,1

In [17]:
input_df = input_df.reindex(columns=loaded_columns, fill_value=0)

In [18]:
input_df

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,48,80,1,0,121,36,1.2,135,4.5,0,...,1,1,0,0,1,0,0,0,0,0

In [19]:
loaded_model.predict(input_df)

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(

array([0])